services:
  api:
    build: .
    container_name: casca_api
    ports:
      - "1028:1028"
      - "1029:1029"
    env_file:
      - config/settings/.env
    volumes:
      - .:/usr/src/app
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
    restart: always
    user: root
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: casca_redis
    volumes:
      - redis_data:/data
    restart: always

  nginx:
    image: nginx:stable-alpine
    container_name: casca_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static
      - ./media:/media
    depends_on:
      - api
    restart: always

volumes:
  redis_data:
