from abc import ABC, abstractmethod
from typing import Protocol, Optional, Iterable
from core.domain.user.entities import UserEntity
from core.domain.order.entities import OrderEntity

class UserRepository(Protocol):
    def get_by_id(self, user_id: int) -> Optional[UserEntity]: ...
    def get_by_email(self, email: str) -> Optional[UserEntity]: ...
    def create(self, email: str) -> UserEntity: ...

class OrderRepository(Protocol):
    def create(self, user_id: int, total: float) -> OrderEntity: ...
    def list_by_user(self, user_id: int) -> Iterable[OrderEntity]: ...
